packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - '@nestjs/core'
  - argon2
